"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("muzakki", [
      {
        nama_lengkap: "Muzakki 1",
        email: "muzakki1@gmail.com",
        nomor_telpon: "081234567801",
        alamat: "Bandung, Jawa Barat",
        npwp: "15.555.678.9-015.001",
        nik: "3201123456789001",
        tempat_lahir: "Bandung",
        tanggal_lahir: "1990-05-15",
        jenis_kelamin: "laki-laki",
        pekerjaan: "Karyawan Swasta",
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
        deleted_status: 0,
      },
      // {
      //   nama_lengkap: "Muzakki 2",
      //   email: "muzakki2@gmail.com",
      //   nomor_telpon: "081234567802",
      //   alamat: "Jakarta, DKI Jakarta",
      //   npwp: "15.555.678.9-015.002",
      //   nik: "3201123456789002",
      //   tempat_lahir: "Jakarta",
      //   tanggal_lahir: "1988-09-10",
      //   jenis_kelamin: "perempuan",
      //   pekerjaan: "Dokter",
      //   created_at: new Date(),
      //   updated_at: null,
      //   deleted_at: null,
      //   deleted_status: 0,
      // },
      // {
      //   nama_lengkap: "Muzakki 3",
      //   email: "muzakki3@gmail.com",
      //   nomor_telpon: "081234567803",
      //   alamat: "Surabaya, Jawa Timur",
      //   npwp: "15.555.678.9-015.003",
      //   nik: "3201123456789003",
      //   tempat_lahir: "Surabaya",
      //   tanggal_lahir: "1995-01-20",
      //   jenis_kelamin: "laki-laki",
      //   pekerjaan: "Pengusaha",
      //   created_at: new Date(),
      //   updated_at: null,
      //   deleted_at: null,
      //   deleted_status: 0,
      // },
      // {
      //   nama_lengkap: "Muzakki 4",
      //   email: "muzakki4@gmail.com",
      //   nomor_telpon: "081234567804",
      //   alamat: "Yogyakarta",
      //   npwp: "15.555.678.9-015.004",
      //   nik: "3201123456789004",
      //   tempat_lahir: "Yogyakarta",
      //   tanggal_lahir: "1992-12-01",
      //   jenis_kelamin: "perempuan",
      //   pekerjaan: "Guru",
      //   created_at: new Date(),
      //   updated_at: null,
      //   deleted_at: null,
      //   deleted_status: 0,
      // },
      // {
      //   nama_lengkap: "Muzakki 5",
      //   email: "muzakki5@gmail.com",
      //   nomor_telpon: "081234567805",
      //   alamat: "Semarang, Jawa Tengah",
      //   npwp: "15.555.678.9-015.005",
      //   nik: "3201123456789005",
      //   tempat_lahir: "Semarang",
      //   tanggal_lahir: "1985-07-25",
      //   jenis_kelamin: "laki-laki",
      //   pekerjaan: "Pegawai Negeri",
      //   created_at: new Date(),
      //   updated_at: null,
      //   deleted_at: null,
      //   deleted_status: 0,
      // },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("muzakki", null, {});
  },
};
