"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const now = new Date();

    await queryInterface.bulkInsert("muzakki", [
      {
        nama_lengkap: "Ahmad Fauzi",
        email: "ahmad.fauzi@example.com",
        nomor_telpon: "082112345001",
        alamat: "Jl. Sukajadi No. 24, Bandung",
        npwp: "12.345.678.9-001.000",
        nik: "3273011201800001",
        tempat_lahir: "Bandung",
        tanggal_lahir: "1980-01-12",
        jenis_kelamin: "laki-laki",
        pekerjaan: "Wiraswasta",
        created_at: now,
        updated_at: null,
        deleted_at: null,
        deleted_status: 0,
      },
      {
        nama_lengkap: "Nurul Hidayah",
        email: "nurul.hidayah@example.com",
        nomor_telpon: "082112345002",
        alamat: "Jl. Setiabudi No. 11, Bandung",
        npwp: "23.456.789.0-002.000",
        nik: "3273014502850002",
        tempat_lahir: "Cirebon",
        tanggal_lahir: "1985-02-05",
        jenis_kelamin: "perempuan",
        pekerjaan: "Guru",
        created_at: now,
        updated_at: null,
        deleted_at: null,
        deleted_status: 0,
      },
      {
        nama_lengkap: "Budi Santoso",
        email: "budi.santoso@example.com",
        nomor_telpon: "082112345003",
        alamat: "Jl. Kopo No. 35, Bandung",
        npwp: "34.567.890.1-003.000",
        nik: "3273011803750003",
        tempat_lahir: "Bandung",
        tanggal_lahir: "1975-03-18",
        jenis_kelamin: "laki-laki",
        pekerjaan: "Pegawai Negeri",
        created_at: now,
        updated_at: null,
        deleted_at: null,
        deleted_status: 0,
      },
      {
        nama_lengkap: "Ratna Puspita",
        email: "ratna.puspita@example.com",
        nomor_telpon: "082112345004",
        alamat: "Jl. Buah Batu No. 19, Bandung",
        npwp: "45.678.901.2-004.000",
        nik: "3273015204900004",
        tempat_lahir: "Sumedang",
        tanggal_lahir: "1990-04-12",
        jenis_kelamin: "perempuan",
        pekerjaan: "Dokter",
        created_at: now,
        updated_at: null,
        deleted_at: null,
        deleted_status: 0,
      },
      {
        nama_lengkap: "Hendra Wijaya",
        email: "hendra.wijaya@example.com",
        nomor_telpon: "082112345005",
        alamat: "Jl. Cihampelas No. 42, Bandung",
        npwp: "56.789.012.3-005.000",
        nik: "3273012206880005",
        tempat_lahir: "Tasikmalaya",
        tanggal_lahir: "1988-06-22",
        jenis_kelamin: "laki-laki",
        pekerjaan: "Karyawan Swasta",
        created_at: now,
        updated_at: null,
        deleted_at: null,
        deleted_status: 0,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("muzakki", null, {});
  },
};
